import { HistoryJob, JobActor, QueueItem, RunningJob } from '../types/api';

const NOW = Date.now();

const minutesAgo = (minutes: number) => new Date(NOW - minutes * 60 * 1000).toISOString();

const person = (login: string): JobActor => ({
  login,
  avatarUrl: `https://avatars.example/${login}`,
});

const LONG_REPOSITORY = 'acme-industries/platform-observability-and-telemetry-pipeline';
const LONG_REPOSITORY_URL =
  'https://github.com/acme-industries/platform-observability-and-telemetry-pipeline';

export const previewQueue: QueueItem[] = [
  {
    id: 900101,
    name: 'build-and-push-container-image',
    workflowName: 'CI',
    branch: 'release/2026.09/hotfix-3',
    actor: person('priya-s'),
    event: 'push',
    repository: LONG_REPOSITORY,
    repositoryUrl: LONG_REPOSITORY_URL,
    scaleSet: 'arc-gpu-a10',
    position: 1,
    createdAt: minutesAgo(3 * 60 + 12),
    waitMs: (3 * 60 + 12) * 60 * 1000,
    htmlUrl: `${LONG_REPOSITORY_URL}/actions/runs/700101/job/900101`,
    runUrl: `${LONG_REPOSITORY_URL}/actions/runs/700101`,
  },
  {
    id: 900102,
    name: 'lint',
    workflowName: 'CI',
    branch: 'feature/telemetry export',
    actor: null,
    event: 'pull_request',
    repository: 'acme/web-app',
    repositoryUrl: 'https://github.com/acme/web-app',
    scaleSet: null,
    position: 1,
    createdAt: minutesAgo(2 * 24 * 60 + 40),
    waitMs: (2 * 24 * 60 + 40) * 60 * 1000,
    htmlUrl: 'https://github.com/acme/web-app/actions/runs/700102/job/900102',
    runUrl: 'https://github.com/acme/web-app/actions/runs/700102',
  },
  {
    id: 900103,
    name: 'package',
    workflowName: 'Release',
    branch: null,
    actor: person('devlin-park'),
    event: 'workflow_dispatch',
    repository: 'acme/infra-tools',
    repositoryUrl: 'https://github.com/acme/infra-tools',
    scaleSet: 'arc-linux-x64',
    position: 2,
    createdAt: minutesAgo(6),
    waitMs: 6 * 60 * 1000,
    htmlUrl: 'https://github.com/acme/infra-tools/actions/runs/700103/job/900103',
    runUrl: 'https://github.com/acme/infra-tools/actions/runs/700103',
  },
  {
    id: 900104,
    name: 'unit-tests',
    workflowName: 'CI',
    branch: 'main',
    actor: person('amira-k'),
    event: 'push',
    repository: 'acme/web-app',
    repositoryUrl: 'https://github.com/acme/web-app',
    scaleSet: 'arc-gpu-a10',
    position: 2,
    createdAt: minutesAgo(48),
    waitMs: 48 * 60 * 1000,
    htmlUrl: 'https://github.com/acme/web-app/actions/runs/700104/job/900104',
    runUrl: 'https://github.com/acme/web-app/actions/runs/700104',
  },
];

export const previewRunning: RunningJob[] = [
  {
    id: 910201,
    name: 'integration-tests-on-real-hardware',
    workflowName: 'Nightly',
    branch: 'feature/runner-autoscaling/phase-2',
    actor: person('priya-s'),
    event: 'schedule',
    repository: LONG_REPOSITORY,
    repositoryUrl: LONG_REPOSITORY_URL,
    runnerName: 'arc-gpu-a10-9f2c1',
    scaleSet: 'arc-gpu-a10',
    startedAt: minutesAgo(3 * 24 * 60 + 5 * 60),
    runningMs: (3 * 24 * 60 + 5 * 60) * 60 * 1000,
    htmlUrl: `${LONG_REPOSITORY_URL}/actions/runs/710201/job/910201`,
    runUrl: `${LONG_REPOSITORY_URL}/actions/runs/710201`,
  },
  {
    id: 910202,
    name: 'short-job',
    workflowName: null,
    branch: null,
    actor: null,
    event: null,
    repository: 'acme/infra-tools',
    repositoryUrl: 'https://github.com/acme/infra-tools',
    runnerName: null,
    scaleSet: null,
    startedAt: null,
    runningMs: null,
    htmlUrl: 'https://github.com/acme/infra-tools/actions/runs/710202/job/910202',
    runUrl: 'https://github.com/acme/infra-tools/actions/runs/710202',
  },
  {
    id: 910203,
    name: 'build',
    workflowName: 'CI',
    branch: 'main',
    actor: person('amira-k'),
    event: 'push',
    repository: 'acme/web-app',
    repositoryUrl: 'https://github.com/acme/web-app',
    runnerName: 'arc-linux-x64-e01a7',
    scaleSet: 'arc-linux-x64',
    startedAt: minutesAgo(9),
    runningMs: 9 * 60 * 1000,
    htmlUrl: 'https://github.com/acme/web-app/actions/runs/710203/job/910203',
    runUrl: 'https://github.com/acme/web-app/actions/runs/710203',
  },
];

export const previewHistory: HistoryJob[] = [
  {
    id: 920301,
    name: 'build-and-push-container-image',
    workflowName: 'CI',
    branch: 'release/2026.09/hotfix-3',
    actor: person('priya-s'),
    event: 'push',
    repository: LONG_REPOSITORY,
    repositoryUrl: LONG_REPOSITORY_URL,
    result: 'success',
    runnerName: 'arc-gpu-a10-9f2c1',
    scaleSet: 'arc-gpu-a10',
    createdAt: minutesAgo(95),
    startedAt: minutesAgo(92),
    completedAt: minutesAgo(30),
    durationMs: 62 * 60 * 1000,
    htmlUrl: `${LONG_REPOSITORY_URL}/actions/runs/720301/job/920301`,
    runUrl: `${LONG_REPOSITORY_URL}/actions/runs/720301`,
  },
  {
    id: 920302,
    name: 'lint',
    workflowName: 'CI',
    branch: 'feature/telemetry export',
    actor: null,
    event: 'pull_request',
    repository: 'acme/web-app',
    repositoryUrl: 'https://github.com/acme/web-app',
    result: 'failure',
    runnerName: 'arc-linux-x64-e01a7',
    scaleSet: 'arc-linux-x64',
    createdAt: minutesAgo(180),
    startedAt: minutesAgo(178),
    completedAt: minutesAgo(176),
    durationMs: 2 * 60 * 1000,
    htmlUrl: 'https://github.com/acme/web-app/actions/runs/720302/job/920302',
    runUrl: 'https://github.com/acme/web-app/actions/runs/720302',
  },
  {
    id: 920303,
    name: 'package',
    workflowName: 'Release',
    branch: null,
    actor: person('devlin-park'),
    event: 'workflow_dispatch',
    repository: 'acme/infra-tools',
    repositoryUrl: 'https://github.com/acme/infra-tools',
    result: 'cancelled',
    runnerName: null,
    scaleSet: null,
    createdAt: minutesAgo(300),
    startedAt: minutesAgo(298),
    completedAt: minutesAgo(291),
    durationMs: 7 * 60 * 1000,
    htmlUrl: 'https://github.com/acme/infra-tools/actions/runs/720303/job/920303',
    runUrl: 'https://github.com/acme/infra-tools/actions/runs/720303',
  },
  {
    id: 920304,
    name: 'integration-tests-on-real-hardware',
    workflowName: 'Nightly',
    branch: 'feature/runner-autoscaling/phase-2',
    actor: person('amira-k'),
    event: 'schedule',
    repository: LONG_REPOSITORY,
    repositoryUrl: LONG_REPOSITORY_URL,
    result: 'timed_out',
    runnerName: 'arc-gpu-a10-16cc2',
    scaleSet: 'arc-gpu-a10',
    createdAt: minutesAgo(4 * 24 * 60),
    startedAt: minutesAgo(4 * 24 * 60 - 1),
    completedAt: minutesAgo(24 * 60),
    durationMs: (3 * 24 * 60 + 1) * 60 * 1000,
    htmlUrl: `${LONG_REPOSITORY_URL}/actions/runs/720304/job/920304`,
    runUrl: `${LONG_REPOSITORY_URL}/actions/runs/720304`,
  },
  {
    id: 920305,
    name: 'unit-tests',
    workflowName: 'CI',
    branch: 'main',
    actor: person('priya-s'),
    event: 'push',
    repository: 'acme/web-app',
    repositoryUrl: 'https://github.com/acme/web-app',
    result: 'other',
    runnerName: 'arc-linux-x64-e01a7',
    scaleSet: 'arc-linux-x64',
    createdAt: minutesAgo(600),
    startedAt: null,
    completedAt: null,
    durationMs: null,
    htmlUrl: 'https://github.com/acme/web-app/actions/runs/720305/job/920305',
    runUrl: 'https://github.com/acme/web-app/actions/runs/720305',
  },
];
